# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - left_wheel_joint
      - right_wheel_joint
   sim_control_mode: 0 # 0: position, 1: velocity
